drop table permission if exists;
drop table role if exists;
drop table role_permission if exists;
drop table user if exists;
drop table user_role if exists;
create table permission (id bigint generated by default as identity, name varchar(255), url varchar(255), primary key (id));
create table role (id bigint generated by default as identity, name varchar(255), primary key (id));
create table role_permission (role_id bigint not null, permission_id bigint not null, primary key (permission_id, role_id));
create table user (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id));
create table user_role (role_id bigint not null, user_id bigint not null, primary key (user_id, role_id));
alter table role_permission add constraint FKf8yllw1ecvwqy3ehyxawqa1qp foreign key (permission_id) references permission;
alter table role_permission add constraint FKa6jx8n8xkesmjmv6jqug6bg68 foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;

